### PR TITLE
Error if broker already exists

### LINKED ISSUE #152: tmctl create broker with same name
tmctl should return an error if I try to create a broker with a name that already exists:

```
⇒  tmctl create broker mybroker
2022/11/25 12:32:21 mybroker | Updating manifest
2022/11/25 12:32:21 mybroker | Starting container
---------------
Created object name:	mybroker
Current broker is set to "mybroker"
To change the current broker use "tmctl brokers --set <broker name>"
```
```
⇒  tmctl create broker mybroker
2022/11/25 12:32:24 mybroker | Updating manifest
2022/11/25 12:32:24 mybroker | Starting container
---------------
Created object name:	mybroker
Current broker is set to "mybroker"
To change the current broker use "tmctl brokers --set <broker name>"
```

### PR DESCRIPTION
**Pull request by FranBarrera**
Closes #152

### CODE REVIEW

**Comment by tzununbekov** [comment]
It doesn't work if I switch between brokers:

```
tmctl@broker-already-exists$ tmctl create broker foo
...
2022/11/25 18:20:16 broker: foo already exists

tmctl@broker-already-exists$ tmctl create broker bar
2022/11/25 18:20:26 foo | Updating manifest
2022/11/25 18:20:26 foo | Starting container
---------------
Created object name:	bar
Current broker is set to "bar"
To change the current broker use "tmctl brokers --set <broker name>"
tmctl@broker-already-exists$ tmctl create broker foo
2022/11/25 18:20:33 bar | Updating manifest
2022/11/25 18:20:33 bar | Starting container
---------------
Created object name:	foo
Current broker is set to "foo"
To change the current broker use "tmctl brokers --set <broker name>"
```

**Comment by FranBarrera** [comment]
> It doesn't work if I switch between brokers:
> 
> ```
> tmctl@broker-already-exists$ tmctl create broker foo
> ...
> 2022/11/25 18:20:16 broker: foo already exists
> 
> tmctl@broker-already-exists$ tmctl create broker bar
> 2022/11/25 18:20:26 foo | Updating manifest
> 2022/11/25 18:20:26 foo | Starting container
> ---------------
> Created object name:	bar
> Current broker is set to "bar"
> To change the current broker use "tmctl brokers --set <broker name>"
> tmctl@broker-already-exists$ tmctl create broker foo
> 2022/11/25 18:20:33 bar | Updating manifest
> 2022/11/25 18:20:33 bar | Starting container
> ---------------
> Created object name:	foo
> Current broker is set to "foo"
> To change the current broker use "tmctl brokers --set <broker name>"
> ```

@tzununbekov But you are not trying to switch between brokers no? You are trying to create the broker foo again, or maybe I miss something.

I've tried to switch between brokers:

```
⇒  tmctl create broker mybroker
Error: broker: mybroker already exists
Usage:
  tmctl create broker <name> [flags]

Flags:
  -h, --help   help for broker

Global Flags:
      --broker string    Optional broker name.
      --version string   TriggerMesh components version.

2022/11/25 15:24:30 broker: mybroker already exists
```
```
⇒  tmctl create broker mybroker2
2022/11/25 15:24:33 mybroker | Updating manifest
2022/11/25 15:24:33 mybroker | Starting container
---------------
Created object name:	mybroker2
Current broker is set to "mybroker2"
To change the current broker use "tmctl brokers --set <broker name>"
```
```
⇒  tmctl brokers --set  mybroker2
mybroker
*mybroker2
```
```
⇒  tmctl brokers --set  mybroker
*mybroker
mybroker2
```

**Comment by tzununbekov** [comment]
Linked issue says:

```
tmctl should return an error if I try to create a broker with a name that already exists
```

If I create two brokers, the fix that you are proposing does not follow the behavior you defined in the issue - it does not tell that the broker already exists. Am I missing something?

**Comment by FranBarrera** [comment]
Oh I see what you mean, I'll check it

**Comment by tzununbekov** [comment]
What is the status of this PR? Can it be reviewed or is it still a draft?

**Comment by FranBarrera** [comment]
@tzununbekov It's ready for review

**Review by tzununbekov — APPROVED** [review]

**Pull request merged**
